# Starter pipeline 
 
trigger:
  - "*"

pr:
  branches:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  system.debug: true

steps:
  - script: |
      echo "This pipeline was triggered by a pull request."
      ls /home/vsts/work/1/s
    displayName: "List Directory"
