# Starter pipeline
#shdh

trigger:
- '*'

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "This pipeline was triggered by a pull"
    ls /home/vsts/work/1/s
  displayName: 'List Directory'
